otus_django/urls.py
from django.contrib import admin
from django.urls import path, include
from hasker import views

urlpatterns = [
    path('', include('questions.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('polls/',  include('polls.urls')),
    path('hasker/', include("hasker.urls")),



]

# if settings.DEBUG:
#     urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'views.handler_404'
handler500 = 'views.handler_500'

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

questions/urls.py
from django.urls import path, re_path

from votes.views import VoteView
from .views import QuestionList, QuestionCreate, QuestionDetail, QuestionSearch, \
    QuestionAnswerAward

app_name = 'questions'

urlpatterns = [
    path('', QuestionList.as_view(), name='index'),
    path('add/', QuestionCreate.as_view(), name='add'),
    path("<int:pk>/", QuestionDetail.as_view(), name='detail'),
    path("search/", QuestionSearch.as_view(), name='search'),
    path("<int:pk>/answer/<int:answer_id>/award/", QuestionAnswerAward.as_view(), name='award'),
    re_path(r"^vote/(?P<object_name>question|answer)/(?P<object_id>\d+)/(?P<vote>up|down)/?$", VoteView.as_view(),
            name='vote')
]

questions/models.py
from django.db import models
from django.urls import reverse_lazy

from users.models import UserProfile
from votes.models import RankedVoteModel
from .managers import QuestionRelationsManager


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name


class Question(RankedVoteModel):
    title = models.CharField(max_length=256)
    content = models.TextField(max_length=1024)
    date_pub = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='questions')
    tags = models.ManyToManyField(Tag, blank=True)

    objects = models.Manager()
    objects_related = QuestionRelationsManager()

    class Meta:
        ordering = ['-date_pub']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('questions:detail', args=[self.pk])


class Answer(RankedVoteModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers', default=None)
    content = models.TextField(max_length=1024)
    date_pub = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='answers')
    is_right = models.BooleanField(default=False, blank=True)

    class Meta:
        ordering = ['-date_pub']

    def __str__(self):
        return self.content
    

questions/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Question, Tag, Answer


class CommaSeparatedTextField(forms.Field):
    widget = forms.TextInput()

    def to_python(self, value):
        tags = []
        if value:
            values = [i.lower() for i in map(str.strip, value.split(',')) if i]
            if len(values) <= 3:
                for tag_name in values:
                    tags.append(Tag.objects.get_or_create(name=tag_name)[0])
                return tags
            else:
                raise ValidationError('Max 3 tags is allowed')
        return tags


class QuestionAddForm(forms.ModelForm):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea, label='Your Question')
    tags = CommaSeparatedTextField(required=False, help_text='You can specify up to 3 tags using a comma')

    class Meta:
        model = Question
        fields = ('title', 'content', 'tags')


class AnswerAddForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, label='Your Answer')

    class Meta:
        model = Answer
        fields = ('content',)

questions/views.py
import logging

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import View, ListView, CreateView

from .forms import QuestionAddForm, AnswerAddForm
from .models import Question, Answer
from .utils import send_email_about_new_answer

logger = logging.getLogger(__name__)


class QuestionList(ListView):
    paginate_by = settings.QUESTIONS_PER_PAGE
    model = Question
    template_name = 'questions/index.html'
    queryset = Question.objects_related.num_answers().tags().users()

    def get_ordering(self):
        order_by = self.request.GET.get('order_by', None)
        if order_by == 'rank':
            ordering = ('-rank', '-date_pub',)
        else:
            ordering = ('-date_pub',)
        return ordering


class QuestionSearch(ListView):
    paginate_by = settings.QUESTIONS_PER_PAGE
    model = Question
    template_name = 'questions/search.html'
    queryset = Question.objects_related.num_answers().tags().users()
    ordering = ('-rank', '-date_pub',)

    def get_queryset(self):
        queryset = self.queryset

        name = self.request.GET.get('t', None)
        if name:
            queryset = queryset.filter(tags__name=name)
        search_str = self.request.GET.get('s', None)
        if search_str:
            if 'tag:' in search_str:
                name = search_str[4:].strip()
                if name:
                    queryset = queryset.filter(tags__name=name)
            else:
                queryset = queryset.filter(Q(title__contains=search_str) | Q(content__contains=search_str))

        ordering = self.get_ordering()
        if ordering:
            if isinstance(ordering, str):
                ordering = (ordering,)
            queryset = queryset.order_by(*ordering)

        return queryset


class QuestionCreate(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionAddForm
    template_name = 'questions/create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(QuestionCreate, self).form_valid(form)


class QuestionDetail(View):
    template_name = 'questions/view.html'
    form_class = AnswerAddForm

    def get_question(self, pk):
        return get_object_or_404(Question.objects.select_related('user'), pk=pk)

    def paginate_answers(self, request, question):
        page = request.GET.get('page')
        answers_list = Answer.objects.filter(question=question). \
            prefetch_related('user'). \
            order_by('-rank', '-date_pub')

        paginator = Paginator(answers_list, settings.ANSWERS_PER_PAGE)
        return paginator.get_page(page)

    def get(self, request, pk):
        question = self.get_question(pk)

        ctx = dict()
        ctx['question'] = question
        ctx['page_obj'] = self.paginate_answers(request, question)
        ctx['form'] = self.form_class()

        return render(request, self.template_name, ctx)

    def post(self, request, pk):
        if not request.user.is_authenticated:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

        question = self.get_question(pk)

        form = self.form_class(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.user = request.user
            answer.save()
            send_email_about_new_answer(self.request, answer, question)
            return redirect(reverse_lazy('questions:detail', kwargs={'pk': pk}))

        ctx = dict()
        ctx['question'] = question
        ctx['page_obj'] = self.paginate_answers(request, question)
        ctx['form'] = self.form_class()
        return render(request, self.template_name, ctx)


class QuestionAnswerAward(LoginRequiredMixin, View):

    def get(self, request, pk, answer_id):
        Answer.objects.filter(pk=answer_id, question_id=pk, question__user=request.user).\
            update(is_right=Q(is_right=False))
        return redirect(request.META.get('HTTP_REFERER'))

questions/templates/questions/create.html
{% extends  'hasker/layouts/layout.html' %}
{% load crispy_forms_tags %}

{% block title %} Ask Question {% endblock %}

{% block left_column %}
<div class="row">
    <div class="col">
        <h1>Ask a Question</h1>
    </div>
</div>

<hr class="mb-3">

<div class="row">
    <div class="col-9">
        <form method="post">
            {% csrf_token %}

            <input type="hidden" name="next" value="{{ next }}">

            {{ form|crispy }}

            <button type="submit" class="btn btn-primary btn-block">Ask</button>
        </form>
    </div>
</div>
{% endblock %}

questions/templates/questions/index.html
{% extends  'hasker/layouts/layout.html' %}
{% load url_replace %}

{% block title %} Questions {% endblock %}

{% block left_column %}
<div class="row">
    <div class="col">
        <h1> All Questions </h1>
    </div>

    <div class="col">

        <ul class="nav nav-tabs mb-3">
            <li class="nav-item">
                <a class="nav-link {% if not request.GET.order_by %}active{% endif %}"
                   href="?{% url_replace order_by='' %}">New</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.GET.order_by == 'rank' %}active{% endif %}"
                   href="?{% url_replace order_by='rank' %}">Hot</a>
            </li>
        </ul>

    </div>

</div>


<div class="row">
    <div class="col">
        {% for question in page_obj %}
        {% include 'questions/include/question_card.html' with question=question %}
        {% endfor %}
    </div>
</div>

<!-- paginator -->
<div class="row">
    <div class="col">
        {% include 'hasker/layouts/paginator.html' %}
    </div>
</div>

{% endblock %}

questions/templates/questions/search.html
{% extends  'hasker/layouts/layout.html' %}
{% load url_replace %}
{% load paginate %}

{% block title %} Search Questions {% endblock %}

{% block left_column %}
<div class="row">
    <div class="col">
        <h1> Search Results </h1>
    </div>
</div>


<div class="row">
    <div class="col">
        {% for question in page_obj %}
        {% include 'questions/include/question_card.html' with question=question %}
        {% endfor %}
    </div>
</div>

<!-- paginator -->
<div class="row">
    <div class="col">
        {% paginate %}
    </div>
</div>

{% endblock %}

questions/templates/questions/trending.html
<div class="row">
    <div class="col-12">
        <a href="{% url 'questions:add' %}" class="btn btn-primary">Ask Question</a>
        <hr class="mb-3"/>
        <h2>Trending Questions</h2>

        <ul class="list-unstyled">
            {% for question in trending %}
            <li class="mb-2">
                <span class="badge badge-info">{{ question.rank }}</span>
                <a href="{% url 'questions:detail' question.pk %}">{{ question.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>