otus_django/urls.py
from django.contrib import admin
from django.urls import path, include
from hasker import views

urlpatterns = [
    path('', include('questions.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('polls/',  include('polls.urls')),
    path('hasker/', include("hasker.urls")),



]

# if settings.DEBUG:
#     urlpatterns += [path('__debug__/', include(debug_toolbar.urls)), ]
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'views.handler_404'
handler500 = 'views.handler_500'

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

questions/urls.py
from django.urls import path, re_path

from votes.views import VoteView
from .views import QuestionList, QuestionCreate, QuestionDetail, QuestionSearch, \
    QuestionAnswerAward

app_name = 'questions'

urlpatterns = [
    path('', QuestionList.as_view(), name='index'),
    path('add/', QuestionCreate.as_view(), name='add'),
    path("<int:pk>/", QuestionDetail.as_view(), name='detail'),
    path("search/", QuestionSearch.as_view(), name='search'),
    path("<int:pk>/answer/<int:answer_id>/award/", QuestionAnswerAward.as_view(), name='award'),
    re_path(r"^vote/(?P<object_name>question|answer)/(?P<object_id>\d+)/(?P<vote>up|down)/?$", VoteView.as_view(),
            name='vote')
]

questions/models.py
from django.db import models
from django.urls import reverse_lazy

from users.models import UserProfile
from votes.models import RankedVoteModel
from .managers import QuestionRelationsManager


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name


class Question(RankedVoteModel):
    title = models.CharField(max_length=256)
    content = models.TextField(max_length=1024)
    date_pub = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='questions')
    tags = models.ManyToManyField(Tag, blank=True)

    objects = models.Manager()
    objects_related = QuestionRelationsManager()

    class Meta:
        ordering = ['-date_pub']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('questions:detail', args=[self.pk])


class Answer(RankedVoteModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers', default=None)
    content = models.TextField(max_length=1024)
    date_pub = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='answers')
    is_right = models.BooleanField(default=False, blank=True)

    class Meta:
        ordering = ['-date_pub']

    def __str__(self):
        return self.content
    

votes/models.py
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import Sum

from users.models import UserProfile


class Vote(models.Model):
    VOTE_UP = 1
    VOTE_DOWN = -1
    VOTE_CHOICES = (
        (VOTE_UP, 'Vote Up'),
        (VOTE_DOWN, 'Vote Down')
    )
    user = models.ForeignKey(UserProfile, related_name='votes', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    vote = models.SmallIntegerField(choices=VOTE_CHOICES)

    def on_vote_change(self):
        content_type = ContentType.objects.get(pk=self.content_type.pk)
        related_obj = content_type.get_object_for_this_type(pk=self.object_id)
        rank = Vote.objects.filter(content_type=self.content_type, object_id=self.object_id). \
            aggregate(rank=Sum('vote'))['rank']
        related_obj.update_rank(rank)


class RankedVoteModel(models.Model):
    votes = GenericRelation(Vote)
    rank = models.IntegerField(blank=True, default=0)

    class Meta:
        abstract = True

    def update_rank(self, rank):
        if not self.pk:
            return
        self.rank = rank or 0
        return self.save()

    def vote(self, user, vote):
        """
        if user not voted:
            set vote (+)
        else:
            if previous_vote == +:
                delete vote (+)
            elif previous_vote == -:
                update vote (- => +)
        """
        content_type = ContentType.objects.get_by_natural_key(self._meta.app_label, self._meta.model_name)
        try:
            previous = Vote.objects.get(user=user, object_id=self.pk, content_type=content_type)
            if previous.vote == vote:
                previous.delete()
            else:
                previous.vote = vote
                previous.save()
        except Vote.DoesNotExist:
            vote_obj = Vote(user=user, object_id=self.pk, content_type=content_type, vote=vote)
            vote_obj.save()

questions/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Question, Tag, Answer


class CommaSeparatedTextField(forms.Field):
    widget = forms.TextInput()

    def to_python(self, value):
        tags = []
        if value:
            values = [i.lower() for i in map(str.strip, value.split(',')) if i]
            if len(values) <= 3:
                for tag_name in values:
                    tags.append(Tag.objects.get_or_create(name=tag_name)[0])
                return tags
            else:
                raise ValidationError('Max 3 tags is allowed')
        return tags


class QuestionAddForm(forms.ModelForm):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea, label='Your Question')
    tags = CommaSeparatedTextField(required=False, help_text='You can specify up to 3 tags using a comma')

    class Meta:
        model = Question
        fields = ('title', 'content', 'tags')


class AnswerAddForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, label='Your Answer')

    class Meta:
        model = Answer
        fields = ('content',)

questions/views.py
import logging

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import View, ListView, CreateView

from .forms import QuestionAddForm, AnswerAddForm
from .models import Question, Answer
from .utils import send_email_about_new_answer

logger = logging.getLogger(__name__)


class QuestionList(ListView):
    paginate_by = settings.QUESTIONS_PER_PAGE
    model = Question
    template_name = 'questions/index.html'
    queryset = Question.objects_related.num_answers().tags().users()

    def get_ordering(self):
        order_by = self.request.GET.get('order_by', None)
        if order_by == 'rank':
            ordering = ('-rank', '-date_pub',)
        else:
            ordering = ('-date_pub',)
        return ordering


class QuestionSearch(ListView):
    paginate_by = settings.QUESTIONS_PER_PAGE
    model = Question
    template_name = 'questions/search.html'
    queryset = Question.objects_related.num_answers().tags().users()
    ordering = ('-rank', '-date_pub',)

    def get_queryset(self):
        queryset = self.queryset

        name = self.request.GET.get('t', None)
        if name:
            queryset = queryset.filter(tags__name=name)
        search_str = self.request.GET.get('s', None)
        if search_str:
            if 'tag:' in search_str:
                name = search_str[4:].strip()
                if name:
                    queryset = queryset.filter(tags__name=name)
            else:
                queryset = queryset.filter(Q(title__contains=search_str) | Q(content__contains=search_str))

        ordering = self.get_ordering()
        if ordering:
            if isinstance(ordering, str):
                ordering = (ordering,)
            queryset = queryset.order_by(*ordering)

        return queryset


class QuestionCreate(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionAddForm
    template_name = 'questions/create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(QuestionCreate, self).form_valid(form)


class QuestionDetail(View):
    template_name = 'questions/view.html'
    form_class = AnswerAddForm

    def get_question(self, pk):
        return get_object_or_404(Question.objects.select_related('user'), pk=pk)

    def paginate_answers(self, request, question):
        page = request.GET.get('page')
        answers_list = Answer.objects.filter(question=question). \
            prefetch_related('user'). \
            order_by('-rank', '-date_pub')

        paginator = Paginator(answers_list, settings.ANSWERS_PER_PAGE)
        return paginator.get_page(page)

    def get(self, request, pk):
        question = self.get_question(pk)

        ctx = dict()
        ctx['question'] = question
        ctx['page_obj'] = self.paginate_answers(request, question)
        ctx['form'] = self.form_class()

        return render(request, self.template_name, ctx)

    def post(self, request, pk):
        if not request.user.is_authenticated:
            return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

        question = self.get_question(pk)

        form = self.form_class(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.user = request.user
            answer.save()
            send_email_about_new_answer(self.request, answer, question)
            return redirect(reverse_lazy('questions:detail', kwargs={'pk': pk}))

        ctx = dict()
        ctx['question'] = question
        ctx['page_obj'] = self.paginate_answers(request, question)
        ctx['form'] = self.form_class()
        return render(request, self.template_name, ctx)


class QuestionAnswerAward(LoginRequiredMixin, View):

    def get(self, request, pk, answer_id):
        Answer.objects.filter(pk=answer_id, question_id=pk, question__user=request.user).\
            update(is_right=Q(is_right=False))
        return redirect(request.META.get('HTTP_REFERER'))

votes/views.py
from django.apps import apps
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect
from django.views.generic import View

from .models import Vote


class VoteView(LoginRequiredMixin, View):
    redirect_field_name = None

    def get(self, request, object_name, object_id, vote):
        votes_map = {
            'up': Vote.VOTE_UP,
            'down': Vote.VOTE_DOWN
        }
        vote = votes_map.get(vote)
        if not vote:
            return HttpResponseBadRequest('Invalid vote value')
        app_label = request.resolver_match.app_name
        try:
            model_cls = apps.get_model(app_label, object_name)
            try:
                model_object = model_cls.objects.get(pk=object_id)
                model_object.vote(request.user, vote)
            except model_cls.DoesNotExist:
                return HttpResponseBadRequest('Invalid object id')
        except LookupError:
            return HttpResponseBadRequest('Invalid object name')
        if request.path != request.META.get('HTTP_REFERER'):
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            return redirect('/')

questions/templates/questions/include/answer_card.html
<div class="row mb-3">
    <div class="col">
        <div class="row">
            <div class="col-1 text-center align-items-center justify-content-center">
                {% include 'questions/include/votes.html' with obj=answer %}
                {% include 'questions/include/award.html' %}
            </div>

            <div class="col-11">
                <p>{{ answer.content|linebreaksbr }}</p>
            </div>
        </div>

        <!-- author -->
        <div class="row">
            <div class="col text-right">
                {% include 'questions/include/user_answered.html' %}
            </div>
        </div>
    </div>
</div>
<hr class="mb-3"/>

questions/templates/questions/include/question_card.html
<div class="row mb-3">
    <div class="col-1 text-center align-items-center justify-content-center">
        <span><h5 class="mb-0">{{ question.rank|default:0 }}</h5> <small>votes</small></span>
        <span><h6 class="mb-0">{{ question.num_answers|default:0 }}</h6> <small>answers</small></span>
    </div>
    <div class="col-11">
        <h3><a href="{% url 'questions:detail' question.pk %}">{{ question.title }}</a></h3>
        <p>{{ question.content | truncatewords:15 }}</p>

        <!-- tags + author -->
        <div class="row">
            <div class="col-4">
                {% for tag in question.tags.all %}
                <a href="{% url 'questions:search' %}?t={{ tag.name }}" class="badge badge-info">{{ tag.name }}</a>
                {% endfor %}
            </div>

            <div class="col-8 text-right">
                {% include 'questions/include/user_asked.html' %}
            </div>
        </div>

    </div>
</div>
<hr class="mb-3"/>

questions/templates/questions/include/user_answered.html
<div>
    <img src="{{ answer.user.thumbnail_url }}" class="user-avatar-small rounded rounded-lg"/>
    <div>
        <small><span class="text-info">{{ answer.user.username }}</span> answered
            {{ answer.date_pub|timesince }} ago</small>
    </div>
</div>

questions/templates/questions/include/user_asked.html
<div>
    <img src="{{ question.user.thumbnail_url }}" class="user-avatar-small rounded rounded-lg" />
    <div>
        <small><span class="text-info">{{ question.user.username }}</span> asked
            {{ question.date_pub|timesince }} ago</small>
    </div>
</div>

questions/templates/questions/include/votes.html
{% load model_name %}
{% load votes %}
{% model_name obj as obj_model_name %}
{% is_user_voted_for model_name=obj_model_name model_pk=obj.pk vote=1 as voted_up %}
{% is_user_voted_for model_name=obj_model_name model_pk=obj.pk vote=-1 as voted_down %}
<ul class="list-unstyled mb-0">
    <li>
        {% if voted_up %}
        <a href="{% url 'questions:vote' obj_model_name obj.pk 'up' %}" class="text-decoration-none text-success"
           title="Discard my vote">
            {% else %}
            <a href="{% url 'questions:vote' obj_model_name obj.pk 'up' %}" class="text-decoration-none text-secondary"
               title="Up vote">
                {% endif %}
                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-chevron-compact-up"
                     fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M7.776 5.553a.5.5 0 0 1 .448 0l6 3a.5.5 0 1 1-.448.894L8 6.56 2.224 9.447a.5.5 0 1 1-.448-.894l6-3z"/>
                </svg>
            </a>
    </li>

    <li>
        <h4>{{ obj.rank|default:0 }}</h4>
    </li>

    <li>
        {% if voted_down %}
        <a href="{% url 'questions:vote' obj_model_name obj.pk 'down' %}" class="text-decoration-none text-success"
           title="Discard my vote">
            {% else %}
            <a href="{% url 'questions:vote' obj_model_name obj.pk 'down' %}"
               class="text-decoration-none text-secondary" title="Down vote">
                {% endif %}
                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-chevron-compact-down"
                     fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M1.553 6.776a.5.5 0 0 1 .67-.223L8 9.44l5.776-2.888a.5.5 0 1 1 .448.894l-6 3a.5.5 0 0 1-.448 0l-6-3a.5.5 0 0 1-.223-.67z"/>
                </svg>
            </a>
    </li>
</ul>